<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-C1US6VV" failures="1" tests="7" name="LoginPageTest" time="56.188" errors="0" timestamp="2024-09-28T09:28:36 IST">
  <testcase classname="tests.LoginPageTest" name="loginPageElementsStatus" time="6.115"/>
  <testcase classname="tests.LoginPageTest" name="welcome" time="5.191">
    <failure type="java.lang.AssertionError" message="Welcome page URL is not correct expected [https://qamoviesapp.ccbp.tech/] but found [https://qamoviesapp.ccbp.tech/login]">
      <![CDATA[java.lang.AssertionError: Welcome page URL is not correct expected [https://qamoviesapp.ccbp.tech/] but found [https://qamoviesapp.ccbp.tech/login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at tests.LoginPageTest.welcome(LoginPageTest.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- welcome -->
  <testcase classname="tests.LoginPageTest" name="loginError" time="5.099"/>
  <testcase classname="tests.LoginPageTest" name="loginError" time="4.309"/>
  <testcase classname="tests.LoginPageTest" name="loginError" time="5.795"/>
  <testcase classname="tests.LoginPageTest" name="loginError" time="4.408"/>
  <testcase classname="tests.LoginPageTest" name="loginError" time="4.104"/>
</testsuite> <!-- LoginPageTest -->
